name: Linux Container Node Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: demoaz204acr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build -f Dockerfile.linux . -t demoaz204acr.azurecr.io/demoaz204webapp:${{ github.sha }}
        docker push demoaz204acr.azurecr.io/demoaz204webapp:${{ github.sha }}     

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'demoaz204webapp'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'demoaz204acr.azurecr.io/demoaz204webapp:${{ github.sha }}'
